name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: 29.1

      - name: Install Eldev
        run: curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh

      - name: Generate index
        run: |
          eldev -s -dtT test

      - name: Get index path
        run: |
          eldev -d exec '(print (format "ROM_PARTY_INDEX_PATH=%s" (rom-party-index-path)))' | tail -n1 | tr -d '"' >> "$GITHUB_ENV"
          echo 'index path ${{ env.ROM_PARTY_INDEX_PATH }}'

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.ROM_PARTY_INDEX_PATH }}
